### ISSUE TITLE
File not available

### ISSUE THREAD

**Issue by Geetima2021** [aaryangupta/VSD-TCL-workshop#1]
I tried executing your code however the TCL file used inside your shell is not available. Please change the name to the TCL script to the one you are using.

![error_aaryan](https://github.com/aaryangupta/VSD-TCL-workshop/assets/63381455/4fe81dea-d0b7-4dea-9870-5ed49701d046)

**Comment by aaryangupta** [comment]
Hi @Geetima2021 , 
it was old script, uploaded by mistake. I have updated the script file, please check.
